# Generated by Django 2.0.6 on 2018-06-24 15:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Edate', models.DateField(blank=True, default=datetime.date.today)),
                ('StartTime', models.DateTimeField(verbose_name='date StartTime')),
                ('EndTime', models.DateTimeField(verbose_name='date EndTime')),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ElectionDate', models.DateField(blank=True, default=datetime.date.today)),
                ('vote', models.IntegerField(default=0)),
                ('elec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Election')),
                ('vid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.Candidate')),
            ],
        ),
    ]
