# Generated by Django 2.0.6 on 2018-06-24 15:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Que', models.CharField(max_length=500)),
                ('mnth', models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(blank=True, default=datetime.date.today)),
                ('reward', models.IntegerField(default=0)),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
                ('v_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.Candidate')),
            ],
        ),
    ]
