# Generated by Django 2.0.6 on 2018-06-24 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cunm', models.CharField(max_length=100)),
                ('cpass', models.CharField(max_length=100)),
                ('candidate_name', models.CharField(max_length=100)),
                ('candidate_dob', models.DateField(blank=True, default=datetime.date.today)),
                ('gender', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=100)),
                ('party_name', models.CharField(max_length=100)),
                ('Description', models.CharField(blank=True, max_length=1000)),
                ('logo', models.ImageField(blank=True, upload_to='img0')),
                ('face', models.ImageField(blank=True, upload_to='img1')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vunm', models.CharField(max_length=100)),
                ('vpass', models.CharField(max_length=100)),
                ('voter_name', models.CharField(max_length=100)),
                ('voter_dob', models.DateField(blank=True, default=datetime.date.today)),
                ('gender', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=100)),
                ('flag', models.IntegerField()),
                ('flag1', models.IntegerField()),
            ],
        ),
    ]
