# Generated by Django 2.0.3 on 2018-06-15 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_dob',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_dob',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
