# Generated by Django 2.0.3 on 2018-04-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_auto_20180323_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='reward',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
