# Generated by Django 2.0.3 on 2018-04-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_candidate_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='flag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
