# Generated by Django 2.0.3 on 2018-04-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0004_voter_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='flag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
